spring:
  config:
    activate:
      on-profile: local
  datasource:
#    url: jdbc:mysql://localhost:3306/payment_eda
    url: jdbc:mysql://mysql-server:3306/payment_eda
    username: root
    password: 1234
  jpa:
    show-sql: true # 콘솔로그로 출력하려면
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 1000
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false


  cloud:
    function:
      definition: kafkaConsumer;
    stream:
      kafka:
        bindings:
          kafkaConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-name: payment_wallet_dlq
        binder:
          #brokers: 127.0.0.1:9092
          brokers: kafka1:9092
      bindings:
        kafkaConsumer-in-0:
          destination: payment # topic
          group: wallet-service
          consumer:
            max-attempts: 3

logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??
    p6spy: info
    com:
      zaxxer:
        hikari: INFO