spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/payment_eda
    username: root
    password: 1234
  jpa:
    show-sql: true # 콘솔로그로 출력하려면
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 1000
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
    open-in-view: false


  cloud:
    function:
      definition: kafkaConsumer;
    stream:
      kafka:
        bindings:
          #          producer-out-0:
          #            producer:
          #              configuration:
          #                key:
          #                  serializer: org.apache.kafka.common.serialization.StringSerializer
          #          kafkaConsumer-in-0:
          #            consumer:
          #              configuration:
          #                key:
          #                  deserializer: org.apache.kafka.common.serialization.StringDeserializer

          kafkaConsumer-in-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
        #          consume-in-0:
        #            consumer:
        #              enable-dlq: true
        #              dlq-name: payment_wallet_dlq
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        #        producer-out-0:
        #          destination: test # topic
        #          contentType: application/json
        #        kafkaConsumer-in-0:
        #          destination: test  # topic
        kafkaConsumer-in-0:
          destination: payment # topic
          group: wallet-service
          consumer:
            max-attempts: 3

logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??
    p6spy: info
    com:
      zaxxer:
        hikari: INFO