spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/highvolumetraffic
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO

